import { generateCitedHindsightDocumentHtml } from "./evidence.mjs";

const text = (value) => typeof value === "string" ? value.trim() : "";
export const MAX_SYNTHESIS_PROMPT_BYTES = 24 * 1024;
export const SYNTHESIS_RESPONSE_RESERVE_TOKENS = 8 * 1024;
const LIMITS = { title: 160, claim: 2000, storyTitle: 160, storyBody: 2000, reference: 100, recommendation: 1000, impact: 500, owner: 200, dependency: 200, criterion: 500 };

function selectedSources(sources) {
  if (!Array.isArray(sources) || sources.length !== 1) throw new Error("Select exactly one conversation.");
  const source = sources[0];
  if (!source || (!source.excluded && !Array.isArray(source.events))) throw new Error("Select exactly one valid conversation.");
  return [source];
}
function sourceReference(source, index) { return text(source?.reference) || `selected-conversation-${index + 1}`; }
function excludedReference(source, index) { return `${sourceReference(source, index)}:excluded`; }
function describeFlow(event) { return [text(event?.category) || "Event", text(event?.timestamp), text(event?.title), text(event?.summary)].filter(Boolean).join(" · "); }
function mapContexts(source) {
  const references = new Map((source.events || []).map((event) => [event?.id, text(event?.evidence?.reference)])); const contexts = new Map();
  for (const edge of source.edges || []) { const from = references.get(edge?.from); const to = references.get(edge?.to); if (!from || !to) continue; const label = text(edge?.label) || "related"; contexts.set(from, [...(contexts.get(from) || []), `${label} → ${to}`]); contexts.set(to, [...(contexts.get(to) || []), `${label} ← ${from}`]); }
  return contexts;
}
function sourceEvidence(sources) { return sources.flatMap((source, index) => {
  if (source.excluded) return [{ reference: excludedReference(source, index), availability: "excluded" }]; const relationships = mapContexts(source);
  return (source.events || []).flatMap((event) => { const reference = text(event?.evidence?.reference); return reference ? [{ reference, context: event.summary, flowContext: describeFlow(event), mapContext: (relationships.get(reference) || []).join("\n") }] : []; });
}); }
function required(value, field, maxLength) { if (typeof value !== "string") throw new Error(`${field} must be a string.`); const result = value.trim(); if (!result) throw new Error(`${field} must not be blank.`); if (Array.from(result).length > maxLength) throw new Error(`${field} must be at most ${maxLength} characters.`); return result; }
function array(value, field, { min = 0, max }) { if (!Array.isArray(value) || value.length < min || value.length > max) throw new Error(`${field} must contain between ${min} and ${max} items.`); return value; }
function references(value, field, allowed, max = 20) { const result = array(value, field, { min: 1, max }).map((item, index) => required(item, `${field}[${index + 1}]`, LIMITS.reference)); if (new Set(result).size !== result.length) throw new Error(`${field} must not contain duplicate references.`); if (result.some((item) => !allowed.has(item))) throw new Error(`${field} cites evidence outside the selected redacted source bundle.`); return result; }
function validateClaims(value, allowed) { return array(value, "claims", { max: 80 }).map((claim, index) => { const label = `Claim ${index + 1}`; if (!claim || typeof claim !== "object" || Array.isArray(claim)) throw new Error(`${label} must be an object.`); const classification = required(claim.classification, `${label} classification`, 32); if (!["direct evidence", "inference"].includes(classification)) throw new Error(`${label} must be explicitly classified as direct evidence or inference.`); return { statement: required(claim.statement, `${label} statement`, LIMITS.claim), classification, evidenceReferences: references(claim.evidenceReferences, `${label} evidenceReferences`, allowed) }; }); }
function validateStorySteps(value, allowed) { if (value === undefined) return []; return array(value, "storySteps", { max: 30 }).map((step, index) => { const label = `Story step ${index + 1}`; if (!step || typeof step !== "object" || Array.isArray(step) || Object.keys(step).length !== 4 || Object.keys(step).some((key) => !["title", "body", "classification", "evidenceReferences"].includes(key))) throw new Error(`${label} is malformed.`); const classification = required(step.classification, `${label} classification`, 32); if (!["direct evidence", "inference"].includes(classification)) throw new Error(`${label} must be explicitly classified as direct evidence or inference.`); return { title: required(step.title, `${label} title`, LIMITS.storyTitle), body: required(step.body, `${label} body`, LIMITS.storyBody), classification, evidenceReferences: references(step.evidenceReferences, `${label} evidenceReferences`, allowed, 3) }; }); }
function validateRecommendations(value, allowed) { return array(value, "recommendations", { max: 40 }).map((item, index) => { const label = `Recommendation ${index + 1}`; if (!item || typeof item !== "object" || Array.isArray(item)) throw new Error(`${label} must be an object.`); const priority = required(item.priority, `${label} priority`, 16); if (!["critical", "high", "medium", "low"].includes(priority)) throw new Error(`${label} priority must be critical, high, medium, or low.`); if (required(item.status, `${label} status`, 32) !== "proposed" || required(item.source, `${label} source`, 32) !== "model-suggestion") throw new Error(`${label} must have status "proposed" and source "model-suggestion".`); return { recommendation: required(item.recommendation, `${label} recommendation`, LIMITS.recommendation), priority, expectedImpact: required(item.expectedImpact, `${label} expectedImpact`, LIMITS.impact), suggestedOwner: required(item.suggestedOwner, `${label} suggestedOwner`, LIMITS.owner), dependencies: array(item.dependencies, `${label} dependencies`, { max: 20 }).map((value, n) => required(value, `${label} dependencies[${n + 1}]`, LIMITS.dependency)), acceptanceCriteria: array(item.acceptanceCriteria, `${label} acceptanceCriteria`, { min: 1, max: 20 }).map((value, n) => required(value, `${label} acceptanceCriteria[${n + 1}]`, LIMITS.criterion)), status: "proposed", source: "model-suggestion", evidenceReferences: references(item.evidenceReferences, `${label} evidenceReferences`, allowed) }; }); }
function validateModelOutput(output, allowed) { if (!output || typeof output !== "object" || Array.isArray(output)) throw new Error("Hindsight model output must be an object."); const keys = Object.keys(output); if (keys.some((key) => !["title", "claims", "storySteps", "recommendations"].includes(key))) throw new Error("Hindsight model output contains unsupported fields."); return { title: output.title === undefined ? undefined : required(output.title, "title", LIMITS.title), claims: validateClaims(output.claims, allowed), storySteps: validateStorySteps(output.storySteps, allowed), recommendations: validateRecommendations(output.recommendations, allowed) }; }
function fallbackClaims(sources) { return sources.flatMap((source, index) => source.excluded ? [{ statement: "A selected conversation was excluded during redaction review.", classification: "direct evidence", evidenceReferences: [excludedReference(source, index)] }] : []); }
function defaultClaims(sources) { return sources.flatMap((source) => { const reference = text(source?.events?.[0]?.evidence?.reference); return reference ? [{ statement: `Selected conversation contains ${source.events.length} inspectable events.`, classification: "direct evidence", evidenceReferences: [reference] }] : []; }); }

export function buildHindsightDocument(sources, modelOutput = undefined) {
  const selected = selectedSources(sources); const evidence = sourceEvidence(selected); const allowed = new Set(evidence.filter((item) => item.availability !== "excluded").map((item) => item.reference)); const model = modelOutput === undefined ? { claims: defaultClaims(selected), storySteps: [], recommendations: [] } : validateModelOutput(modelOutput, allowed);
  return generateCitedHindsightDocumentHtml({ title: model.title || "Hindsight source bundle — selected conversation", claims: [...model.claims, ...fallbackClaims(selected)], storySteps: model.storySteps, recommendations: model.recommendations, evidence });
}
export function buildSynthesisPrompt(sources) {
  const selected = selectedSources(sources); const evidence = sourceEvidence(selected); const included = evidence.filter((item) => item.availability !== "excluded"); const excluded = evidence.filter((item) => item.availability === "excluded").map((item) => item.reference);
  return `Create a rigorous hindsight analysis from ONLY the selected conversation's redacted source bundle below. Every material claim and recommendation must cite exact included evidence references. Do not invent facts or use content outside this bundle.\n\nDo NOT write HTML or use a file-writing tool. Call hindsight_document_write exactly once with a short title, structured claims, optional structured storySteps, and structured recommendations. Claims and storySteps must be classified direct evidence or inference and cite included evidence. Recommendations must include recommendation, priority (critical, high, medium, or low), expectedImpact, suggestedOwner, dependencies, acceptanceCriteria, status "proposed", source "model-suggestion", and evidenceReferences. The safe contract escapes model text and creates all local citation links and evidence context.\n\nREDACTED SOURCE BUNDLE:\n${JSON.stringify(included)}\n\nEXCLUDED SELECTION REFERENCES (do not cite):\n${JSON.stringify(excluded)}`;
}
export function preflightSynthesisPrompt(sources, _options, contextUsage) { const prompt = buildSynthesisPrompt(sources); const bytes = Buffer.byteLength(prompt, "utf8"); if (bytes > MAX_SYNTHESIS_PROMPT_BYTES) throw new Error(`Selected redacted evidence is ${bytes.toLocaleString()} bytes; hindsight submissions are limited to ${MAX_SYNTHESIS_PROMPT_BYTES.toLocaleString()} bytes. Select a shorter conversation, then retry.`); const window = contextUsage?.contextWindow; const used = contextUsage?.tokens; if (!Number.isFinite(window) || window <= 0 || !Number.isFinite(used) || used < 0) throw new Error("Unable to determine the active model's context capacity. Run /compact (or start a fresh session), send a short message, then retry hindsight generation."); const available = Math.floor(window - used - SYNTHESIS_RESPONSE_RESERVE_TOKENS); if (available < bytes) throw new Error(`Hindsight needs up to ${bytes.toLocaleString()} conservative context tokens, but only ${Math.max(0, available).toLocaleString()} are available after reserving room for the report. Run /compact or start a fresh session, then retry.`); return prompt; }
