import { generateCitedHindsightDocumentHtml } from "./evidence.mjs";

const text = (value) => typeof value === "string" ? value.trim() : "";
export const MAX_SYNTHESIS_PROMPT_BYTES = 24 * 1024;
export const SYNTHESIS_RESPONSE_RESERVE_TOKENS = 8 * 1024;
const LIMITS = { title: 160, claim: 2000, storyTitle: 160, storyBody: 2000, reference: 100, recommendation: 1000, impact: 500, owner: 200, dependency: 200, criterion: 500, subagentFinding: 2000 };

function selectedSources(sources) {
  if (!Array.isArray(sources) || sources.length !== 1) throw new Error("Select exactly one conversation.");
  const source = sources[0];
  if (!source || (!source.excluded && !Array.isArray(source.events))) throw new Error("Select exactly one valid conversation.");
  return [source];
}
function sourceReference(source, index) { return text(source?.reference) || `selected-conversation-${index + 1}`; }
function excludedReference(source, index) { return `${sourceReference(source, index)}:excluded`; }
function describeEvent(event) { return [text(event?.category) || "Event", text(event?.timestamp), text(event?.title), text(event?.summary)].filter(Boolean).join(" · "); }
function visibleEventSummary(event) { const metadata = (event?.metadata || []).map((item) => `${text(item?.label)}: ${text(item?.value)}`).filter(Boolean); return [text(event?.summary), ...metadata].filter(Boolean).join(" · "); }
function relationshipContexts(source) {
  const references = new Map((source.events || []).map((event) => [event?.id, text(event?.evidence?.reference)])); const contexts = new Map();
  for (const edge of source.edges || []) { const from = references.get(edge?.from); const to = references.get(edge?.to); if (!from || !to) continue; const label = text(edge?.label) || "related"; contexts.set(from, [...(contexts.get(from) || []), `${label} → ${to}`]); contexts.set(to, [...(contexts.get(to) || []), `${label} ← ${from}`]); }
  return contexts;
}
function sourceEvidence(sources) { return sources.flatMap((source, index) => {
  if (source.excluded) return [{ reference: excludedReference(source, index), availability: "excluded" }]; const relationships = relationshipContexts(source);
  return (source.events || []).flatMap((event) => { const reference = text(event?.evidence?.reference); return reference ? [{ reference, context: visibleEventSummary(event), eventContext: describeEvent(event), relationshipContext: (relationships.get(reference) || []).join("\n"), ...(event?.subagentActivity ? { subagentActivity: event.subagentActivity } : {}) }] : []; });
}); }
function subagentReferences(evidence) { return new Set(evidence.filter((item) => ["delegation-call", "delegation-result"].includes(item?.subagentActivity)).map((item) => item.reference)); }
function required(value, field, maxLength) { if (typeof value !== "string") throw new Error(`${field} must be a string.`); const result = value.trim(); if (!result) throw new Error(`${field} must not be blank.`); if (Array.from(result).length > maxLength) throw new Error(`${field} must be at most ${maxLength} characters.`); return result; }
function array(value, field, { min = 0, max }) { if (!Array.isArray(value) || value.length < min || value.length > max) throw new Error(`${field} must contain between ${min} and ${max} items.`); return value; }
function references(value, field, allowed, max = 20) { const result = array(value, field, { min: 1, max }).map((item, index) => required(item, `${field}[${index + 1}]`, LIMITS.reference)); if (new Set(result).size !== result.length) throw new Error(`${field} must not contain duplicate references.`); if (result.some((item) => !allowed.has(item))) throw new Error(`${field} cites evidence outside the selected redacted source bundle.`); return result; }
function validateClaims(value, allowed) { return array(value, "claims", { max: 80 }).map((claim, index) => { const label = `Claim ${index + 1}`; if (!claim || typeof claim !== "object" || Array.isArray(claim)) throw new Error(`${label} must be an object.`); const classification = required(claim.classification, `${label} classification`, 32); if (!["direct evidence", "inference"].includes(classification)) throw new Error(`${label} must be explicitly classified as direct evidence or inference.`); return { statement: required(claim.statement, `${label} statement`, LIMITS.claim), classification, evidenceReferences: references(claim.evidenceReferences, `${label} evidenceReferences`, allowed) }; }); }
function validateStorySteps(value, allowed) { if (value === undefined) return []; return array(value, "storySteps", { max: 30 }).map((step, index) => { const label = `Story step ${index + 1}`; if (!step || typeof step !== "object" || Array.isArray(step) || Object.keys(step).length !== 4 || Object.keys(step).some((key) => !["title", "body", "classification", "evidenceReferences"].includes(key))) throw new Error(`${label} is malformed.`); const classification = required(step.classification, `${label} classification`, 32); if (!["direct evidence", "inference"].includes(classification)) throw new Error(`${label} must be explicitly classified as direct evidence or inference.`); return { title: required(step.title, `${label} title`, LIMITS.storyTitle), body: required(step.body, `${label} body`, LIMITS.storyBody), classification, evidenceReferences: references(step.evidenceReferences, `${label} evidenceReferences`, allowed, 3) }; }); }
function validateRecommendations(value, allowed) { return array(value, "recommendations", { max: 40 }).map((item, index) => { const label = `Recommendation ${index + 1}`; if (!item || typeof item !== "object" || Array.isArray(item)) throw new Error(`${label} must be an object.`); const actionType = required(item.actionType, `${label} actionType`, 16); if (!["fix", "harden"].includes(actionType)) throw new Error(`${label} actionType must be fix or harden.`); const priority = required(item.priority, `${label} priority`, 16); if (!["critical", "high", "medium", "low"].includes(priority)) throw new Error(`${label} priority must be critical, high, medium, or low.`); if (required(item.status, `${label} status`, 32) !== "proposed" || required(item.source, `${label} source`, 32) !== "model-suggestion") throw new Error(`${label} must have status "proposed" and source "model-suggestion".`); return { recommendation: required(item.recommendation, `${label} recommendation`, LIMITS.recommendation), actionType, priority, expectedImpact: required(item.expectedImpact, `${label} expectedImpact`, LIMITS.impact), suggestedOwner: required(item.suggestedOwner, `${label} suggestedOwner`, LIMITS.owner), dependencies: array(item.dependencies, `${label} dependencies`, { max: 20 }).map((value, n) => required(value, `${label} dependencies[${n + 1}]`, LIMITS.dependency)), acceptanceCriteria: array(item.acceptanceCriteria, `${label} acceptanceCriteria`, { min: 1, max: 20 }).map((value, n) => required(value, `${label} acceptanceCriteria[${n + 1}]`, LIMITS.criterion)), status: "proposed", source: "model-suggestion", evidenceReferences: references(item.evidenceReferences, `${label} evidenceReferences`, allowed) }; }); }
function validateSubagentFindings(value, category, qualified, recommendations) {
  if (value === undefined) return [];
  return array(value, `subagentEfficiency.${category}`, { max: 20 }).map((finding, index) => {
    const label = `Subagent ${category} finding ${index + 1}`;
    if (!finding || typeof finding !== "object" || Array.isArray(finding) || Object.keys(finding).length !== 4 || Object.keys(finding).some((key) => !["statement", "findingKind", "classification", "evidenceReferences"].includes(key))) throw new Error(`${label} is malformed.`);
    const findingKind = required(finding.findingKind, `${label} findingKind`, 16);
    if (!["strength", "risk"].includes(findingKind)) throw new Error(`${label} findingKind must be strength or risk.`);
    const classification = required(finding.classification, `${label} classification`, 32);
    if (!["direct evidence", "inference"].includes(classification)) throw new Error(`${label} must be explicitly classified as direct evidence or inference.`);
    const refs = references(finding.evidenceReferences, `${label} evidenceReferences`, qualified);
    const actionType = findingKind === "strength" ? "harden" : "fix";
    if (!recommendations.some((recommendation) => recommendation.actionType === actionType && recommendation.evidenceReferences.some((reference) => refs.includes(reference)))) throw new Error(`Each subagent ${findingKind} finding requires a matching ${actionType} proposal sharing cited evidence.`);
    return { statement: required(finding.statement, `${label} statement`, LIMITS.subagentFinding), findingKind, classification, evidenceReferences: refs };
  });
}
function validateSubagentEfficiency(value, qualified, recommendations) {
  if (value === undefined) return undefined;
  if (!qualified.size) throw new Error("subagentEfficiency must be omitted because this selected conversation has no inspectable subagent activity.");
  if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== 2 || Object.keys(value).some((key) => !["delegationTiming", "deliveryQuality"].includes(key))) throw new Error("subagentEfficiency is malformed.");
  return { delegationTiming: validateSubagentFindings(value.delegationTiming, "delegationTiming", qualified, recommendations), deliveryQuality: validateSubagentFindings(value.deliveryQuality, "deliveryQuality", qualified, recommendations) };
}
function validateModelOutput(output, allowed, qualified) {
  if (!output || typeof output !== "object" || Array.isArray(output)) throw new Error("Hindsight model output must be an object.");
  const keys = Object.keys(output); if (keys.some((key) => !["title", "claims", "storySteps", "recommendations", "subagentEfficiency"].includes(key))) throw new Error("Hindsight model output contains unsupported fields.");
  const claims = validateClaims(output.claims, allowed); const recommendations = validateRecommendations(output.recommendations, allowed);
  for (const claim of claims) {
    const requiredType = claim.classification === "direct evidence" ? "harden" : "fix";
    if (!recommendations.some((recommendation) => recommendation.actionType === requiredType && recommendation.evidenceReferences.some((reference) => claim.evidenceReferences.includes(reference)))) throw new Error(`Each ${claim.classification} claim requires a matching ${requiredType} proposal sharing cited evidence.`);
  }
  return { title: output.title === undefined ? undefined : required(output.title, "title", LIMITS.title), claims, storySteps: validateStorySteps(output.storySteps, allowed), recommendations, subagentEfficiency: validateSubagentEfficiency(output.subagentEfficiency, qualified, recommendations) };
}
function fallbackClaims(sources) { return sources.flatMap((source, index) => source.excluded ? [{ statement: "A selected conversation was excluded during redaction review.", classification: "direct evidence", evidenceReferences: [excludedReference(source, index)] }] : []); }
function defaultClaims(sources) { return sources.flatMap((source) => { const reference = text(source?.events?.[0]?.evidence?.reference); return reference ? [{ statement: `Selected conversation contains ${source.events.length} inspectable events.`, classification: "direct evidence", evidenceReferences: [reference] }] : []; }); }

export function buildHindsightDocument(sources, modelOutput = undefined) {
  const selected = selectedSources(sources); const evidence = sourceEvidence(selected); const allowed = new Set(evidence.filter((item) => item.availability !== "excluded").map((item) => item.reference)); const qualified = subagentReferences(evidence); const model = modelOutput === undefined ? { claims: defaultClaims(selected), storySteps: [], recommendations: [], subagentEfficiency: undefined } : validateModelOutput(modelOutput, allowed, qualified);
  return generateCitedHindsightDocumentHtml({ title: model.title || "Hindsight source bundle — selected conversation", claims: [...model.claims, ...fallbackClaims(selected)], storySteps: model.storySteps, recommendations: model.recommendations, subagentEfficiency: model.subagentEfficiency, evidence });
}
export function buildSynthesisPrompt(sources) {
  const selected = selectedSources(sources); const evidence = sourceEvidence(selected); const included = evidence.filter((item) => item.availability !== "excluded"); const excluded = evidence.filter((item) => item.availability === "excluded").map((item) => item.reference); const qualified = [...subagentReferences(included)];
  const subagentInstruction = qualified.length
    ? `\n\nThe bundle marks exact saved-session subagent delegation calls/results. When the marked evidence supports a finding, optionally include subagentEfficiency with bounded delegationTiming and deliveryQuality arrays. Assess timing separately (useful/appropriate versus late, premature, unnecessary, or missed opportunity) and delivery quality separately against the observed task/contract and follow-up evidence. These are hindsight assessments, never deterministic scores; classify every finding as direct evidence or inference. Each finding has statement, findingKind (strength or risk), classification, and evidenceReferences. Cite ONLY these marked delegation references: ${JSON.stringify(qualified)}. A strength requires a Harden proposal and a risk requires a Fix proposal that shares a cited reference. Include one or more findings in each category only when that category is supported; use an empty array for an unsupported category and omit the entire field when neither category is supported. isError false alone does not prove delivery quality.`
    : `\n\nNo inspectable subagent activity exists in this selected conversation. Omit subagentEfficiency entirely; do not infer delegation from prose, near tool names, or other tools.`;
  return `Create a rigorous hindsight analysis from ONLY the selected conversation's redacted source bundle below. Every material claim and recommendation must cite exact included evidence references. Do not invent facts or use content outside this bundle.\n\nDo NOT write HTML or use a file-writing tool. Call hindsight_document_write exactly once with a short title, structured claims, optional structured storySteps, and structured recommendations. Claims and storySteps must be classified direct evidence or inference and cite included evidence. Recommendations must include actionType ("fix" or "harden"), recommendation, priority (critical, high, medium, or low), expectedImpact, suggestedOwner, dependencies, acceptanceCriteria, status "proposed", source "model-suggestion", and evidenceReferences. For every surfaced direct-evidence strength, include at least one Harden proposal sharing one of its cited evidence references. For every surfaced inference lesson or risk, include at least one Fix proposal sharing one of its cited evidence references. The safe contract escapes model text and creates all local citation links and evidence context.${subagentInstruction}\n\nREDACTED SOURCE BUNDLE:\n${JSON.stringify(included)}\n\nEXCLUDED SELECTION REFERENCES (do not cite):\n${JSON.stringify(excluded)}`;
}
export function preflightSynthesisPrompt(sources, _options, contextUsage) { const prompt = buildSynthesisPrompt(sources); const bytes = Buffer.byteLength(prompt, "utf8"); if (bytes > MAX_SYNTHESIS_PROMPT_BYTES) throw new Error(`Selected redacted evidence is ${bytes.toLocaleString()} bytes; hindsight submissions are limited to ${MAX_SYNTHESIS_PROMPT_BYTES.toLocaleString()} bytes. Select a shorter conversation, then retry.`); const window = contextUsage?.contextWindow; const used = contextUsage?.tokens; if (!Number.isFinite(window) || window <= 0 || !Number.isFinite(used) || used < 0) throw new Error("Unable to determine the active model's context capacity. Run /compact (or start a fresh session), send a short message, then retry hindsight generation."); const available = Math.floor(window - used - SYNTHESIS_RESPONSE_RESERVE_TOKENS); if (available < bytes) throw new Error(`Hindsight needs up to ${bytes.toLocaleString()} conservative context tokens, but only ${Math.max(0, available).toLocaleString()} are available after reserving room for the report. Run /compact or start a fresh session, then retry.`); return prompt; }
